services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${IMAGE_NAME}
    env_file: .env
    ports:
      - "${PORT_HOST}:${PORT_CONTAINER}"
    volumes:
      - ./${PROJECT_NAME}:/app
    stdin_open: true
    tty: true
    environment:
      - PORT=${PORT_CONTAINER}

volumes:
  node_modules:
